version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.15.3 
    steps:
      - checkout
      - run: echo "installing"
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run: echo "test"
      - run: npm install
      - run: npm test
workflows:
  version: 2
  build_test_lint:
    jobs:
      - build
      - test